- id: '1567471864851'
  alias: Sprinkler on
  trigger:
  - at: '20:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data: {}
    service: switch.turn_on
- id: '1567488060908'
  alias: Sprinkler off
  trigger:
  - at: '20:35'
    platform: time
  condition: []
  action:
  - alias: ''
    data: {}
    service: switch.turn_off
- id: '1568524762572'
- alias: Light on if motion
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_Pir
    to: 'on'
  action:
  - service: timer.start
    entity_id: timer.timer_lamp
  - service: switch.turn_on
    entity_id: switch.Garage_Lights
  id: f5d7bb738c4f4e639095a61fcb3327d8
- alias: Turn off lights at end of timer
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_lamp
  action:
    service: switch.turn_off
    entity_id: switch.Garage_Lights
  id: 0ae247630a25407c9d09353289ad2eb2
- id: '1568577814494'
  alias: New Automation
  trigger:
  - entity_id: binary_sensor.water
    platform: state
    to: 'On'
  condition: []
  action:
  - service: logbook.log
- id: '1568577855560'
  alias: New Automation
  trigger:
  - entity_id: binary_sensor.water
    platform: state
    to: 'On'
  condition: []
  action:
  - service: notify.mobile_app_mischa_s_pixel_3a
