# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  packages: !include_dir_named packages/
script: !include_dir_named scripts/
group: !include groups.yaml
discovery:
# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: 10.0.0.160
  username: mqtt
  password: !secret mqtt_pass
binary_sensor:
  - platform: rpi_gpio 
    invert_logic: true
    ports:
      17: Rack Lights
      16: Under House Light 
      27: Outside Lights
      22: Bluetooth Garage
      23: Garage Pir
      24: water
      12: GHL Real
      20: GL Real  
      5: Garage Shelf
      6: Box 
switch:
  - platform: rpi_gpio 
    ports:
     17: Rack Lights
     16: Under House Light
     27: Outside Lights
     22: Bluetooth Garage
     12: GHL Real
     20: Gl Real
     5: Garage Shelf
     6: Box
  - platform: mqtt
    name: "Master_Bed"
    state_topic: "house/interior/groundfloor/output/Master_Bed"
    command_topic: "house/interior/groundfloor/output/Master_Bed/set"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: template
    switches:
      garage_lights:
        value_template: "{{ is_state('switch.gl_real', 'off') }}" # fake switch is on when garage lights switch reports off, and vice versa
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.gl_real
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.gl_real
      garage_hall_lights:
        value_template: "{{ is_state('switch.ghl_real', 'off') }}" # fake switch is on when garage lights switch reports off, and vice versa
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.ghl_real
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.ghl_real        
sensor:
  - platform: onewire
    names:
      28-03069779d752: Rack Temp
      28-0306977997a9: Hallway Temp
      28-03069779b6d7: Box Temp
timer:
  timer_lamp:
    duration: '00:10:15'