automation:
# motion light 
- id: '1568524762572'
  alias: Light on if motion
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_pir
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.timer_lamp
    - service: switch.turn_on
      entity_id: switch.garage_lights
- alias: Turn off lights at end of timer
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.timer_lamp
  action:
    service: switch.turn_off
    entity_id: 
      - switch.garage_lights
      - switch.garage_hall_lights

#turn off lights on reboot, due to relay config they default to on when rebooted
- id: '1570941020623'
  alias: Reboot Turn Off AC Lights
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
    service: switch.turn_off
    entity_id: 
      - switch.garage_lights
      - switch.garage_hall_lights